name: WakaStats

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_OS: "False" 
          SHOW_LOC_CHART: "False" 
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_LANGUAGE_PER_REPO: "True"  
          SHOW_TIMEZONE: "False" 
          LOCALE: "en"
